### ISSUE TITLE
issues with the implementation of ymsp in karabiner.edn

### ISSUE THREAD

**Issue by faustozamparelli** [leonsilicon/macos-configs#1]
I am using your config but I am having by problem trying to implement your ymsp package. I have the exact same configuration for karabiner.edn using goku but the only thing not working is the ymsp  
  
In your config you have these lines
```
			;; super + j: focus down
			[:!CTO#QWEc "ymsp focus-down-window > /dev/null"]
			[:!QWE#CTOc "/Users/leonsilicon/Library/pnpm/ymsp focus-down-window > /dev"
```
I don't understand why in one line you used ymsp directly and in the other the path... 

I have installed it using npm instead of pnpm like you and this are my lines
```
			;; super + j: focus down
			[:!CTO#QWEc "/opt/homebrew/bin/ymsp focus-down-window > /dev/null"]
			[:!QWE#CTOc "/opt/homebrew/bin/ymsp focus-down-window > /dev/null"]
```

They are not working in any way

And often if i run like:
```
❯ ymsp close-focused-window
file:///opt/homebrew/lib/node_modules/yabai-master-stack-plugin/utils/lock.js:26
            throw new Error('Could not acquire lock.');
                  ^

Error: Could not acquire lock.
    at acquireLock (file:///opt/homebrew/lib/node_modules/yabai-master-stack-plugin/utils/lock.js:26:19)
    at acquireHandlerLock (file:///opt/homebrew/lib/node_modules/yabai-master-stack-plugin/utils/handler.js:6:5)
    at main (file:///opt/homebrew/lib/node_modules/yabai-master-stack-plugin/utils/main.js:16:5)
    at file:///opt/homebrew/lib/node_modules/yabai-master-stack-plugin/fns/close-focused-window.js:2:1
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async Command.<anonymous> (file:///opt/homebrew/lib/node_modules/yabai-master-stack-plugin/bin/run.js:19:5)

Node.js v21.7.1
```
I get this error because for some reason there are multiple instances running
```
❯ ps aux | grep ymsp
faustozamparelli  4883   5.5  0.3 422951360  97600   ??  S<    8:15PM   0:35.22 node /opt/homebrew/bin/ymsp window-moved
faustozamparelli 91318   0.0  0.0 410724048   1344 s001  S+    8:25PM   0:00.00 grep --color=auto ymsp
```

For some reason when i press command + j (the super key) it expands the current window to the left a bit

I need help debugging this

**Comment by leonsilicon** [comment]
I just updated yabai-master-stack-plugin to use Bun and updated my goku config; see if the new changes work for you (also you can check Karabiner logs for any issues with ymsp :)

**Comment by faustozamparelli** [comment]
That solved it! Thanks a lot man...

Uninstalled it through npm and now installed it through bun
```
[:!CTO#QWEj "/opt/homebrew/bin/bun /Users/faustozamparelli/.bun/bin/ymsp focus-down-window > /dev/null"]
```
I guess the missing part was that I was not adding the path to bun or npm before giving the path to ymsp. Now it works.

Let me tell you man, that you are a huge inspiration and that I really appreciate your work.
I don't know if this is a great place to ask you but I am also interested for the future to change keyboard layout, form QWERTY to something like COLEMAK DH, I know that you use Dvorak. Would you recommend going trough the pain of changing layout? Are you liking Dvorak and you would you recommend it for programming?

**Comment by leonsilicon** [comment]
Thanks so much for the kind words :)

I'm personally really happy that I switched layouts; I find (programmer) dvorak much more natural/comfortable to type on (and I know a friend who had wrist issues that went away after switching from QWERTY to Dvorak). I'd only recommend against it if you use other people's computers often and/or have concerns with using keybinds/shortcuts such as vim (although this is less of a problem I've heard with Colemak which preserves the position of the Z, X, and C keys, though I'm not sure about vim)

Also make sure you have the time to really commit to forcing yourself to learn an alternate keyboard layout; it took me 2-3 weeks of forcing myself to only use Dvorak to get back to my QWERTY speed (which was ~90wpm at the time) so I'm not sure how long it'd take if you had to switch between layouts daily (e.g. for work), though I do know some people who can type on both layouts (though I'm not sure if I'd recommend that haha)
